import {beforeEach,afterEach,it,expect,vi} from "vitest";
import type {ToolSet} from "ai";
import {AnswersSchema} from "@/app/(public)/check/steps";
import {processCandidates} from "@/scripts/process.rules";
import {version,answers} from "@/lib/rules/__tests__/assessment-fixtures";
const mocks=vi.hoisted(()=>({embed:vi.fn(),streamText:vi.fn(),getProfile:vi.fn(),listRuleVersions:vi.fn(),matchKbRuleHints:vi.fn(),listTasks:vi.fn(),listApplicationsWithCourses:vi.fn()}));
vi.mock("ai",async original=>({...await original<typeof import("ai")>(),embed:mocks.embed,streamText:mocks.streamText,convertToModelMessages:async()=>[]}));
vi.mock("@openrouter/ai-sdk-provider",()=>({createOpenRouter:()=>Object.assign(()=>"mock-chat",{textEmbeddingModel:()=>"mock-embedding"})}));
vi.mock("@/lib/db/queries",()=>mocks);
import {runAssistant} from "../assistant";
const id="89985eb6-d3a6-41ce-879d-fc4bf4e206c9";
const savedAnswers={...answers,hasExistingApsCertificate:false};
const context={version:1,purpose:"study",mission:"new_delhi",missionConfirmed:true,fundingMethod:"blocked_account",exception:"none",ageBracket:"over18"};
const clone=(index:number)=>version(1,{id:"0de37e64-0347-44a9-97c2-09b51454f1a9",rule_id:id,published_at:"2026-10-08T02:24:14Z",reviewed_at:"2026-10-08T02:24:14Z",raw_snapshot:{...processCandidates[index],id,slug:processCandidates[index].id,country_code:processCandidates[index].country,status:"verified"}});
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date("2026-10-08T02:25:00Z"));mocks.embed.mockResolvedValue({embedding:[0,1]});mocks.streamText.mockReturnValue({});mocks.getProfile.mockResolvedValue({answers:{...savedAnswers,visaApplicationCountry:"in",processContext:context}});mocks.listRuleVersions.mockResolvedValue([clone(0)]);mocks.matchKbRuleHints.mockResolvedValue([{rule_id:id,content:"11904 cached false payable"},{rule_id:null,content:"8400 trusted curated snippet"}]);mocks.listTasks.mockResolvedValue([{title:"My old 8400 INR reminder",description:null,source_url:null,due_date:null,done:false}]);mocks.listApplicationsWithCourses.mockResolvedValue([]);});
afterEach(()=>{vi.useRealTimers();vi.resetAllMocks();});
async function tools(){await runAssistant({db:{from:vi.fn(),rpc:vi.fn()},userId:"mock-only",countryCode:"in",messages:[],openrouterApiKey:"mock-only-no-provider"});return mocks.streamText.mock.calls[0][0].tools as ToolSet;}
const callContext={toolCallId:"mock",messages:[],context:{}};
it("tool projections use one immutable/profile snapshot and label saved reminders untrusted",async()=>{const parsed=AnswersSchema.safeParse({ ...savedAnswers,visaApplicationCountry:"in",processContext:context});if(!parsed.success)throw Error(JSON.stringify(parsed.error.issues));const t=await tools();const search=await t.search_rules.execute!({query:"my funding"},callContext);expect(JSON.stringify(search)).toContain("11,904.—");expect(JSON.stringify(search)).not.toContain("cached false payable");mocks.getProfile.mockResolvedValue(null);const current=await t.get_user_context.execute!({},callContext) as {currentProcess:unknown;taskEvidence:string;tasks:unknown};expect(JSON.stringify(current.currentProcess)).toContain("11,904.—");expect(current.taskEvidence).toContain("Personal saved reminders");expect(JSON.stringify(current.tasks)).toContain("My old 8400 INR reminder");expect(mocks.getProfile).toHaveBeenCalledOnce();expect(mocks.listRuleVersions).toHaveBeenCalledOnce();});
it.each(["loan","scholarship","commitment","unknown"])("mock tool cannot disclose blocked-account quote for %s",async fundingMethod=>{mocks.getProfile.mockResolvedValue({answers:{...savedAnswers,visaApplicationCountry:"in",processContext:{...context,fundingMethod}}});const t=await tools();const r=await t.search_rules.execute!({query:"funding"},callContext);expect(JSON.stringify(r)).not.toContain("11,904");const c=await t.get_user_context.execute!({},callContext) as {currentProcess:unknown};expect(JSON.stringify(c.currentProcess)).not.toContain("11,904");});
it("conflicting fee and exactly18 do not disclose raw quotes or curated amounts",async()=>{mocks.listRuleVersions.mockResolvedValue([clone(1)]);mocks.getProfile.mockResolvedValue({answers:{...savedAnswers,visaApplicationCountry:"in",processContext:{...context,ageBracket:"exact18"}}});const t=await tools();expect(JSON.stringify(await t.search_rules.execute!({query:"fee"},callContext))).not.toMatch(/8300|8400|75,--/);const c=await t.get_user_context.execute!({},callContext) as {currentProcess:unknown};expect(JSON.stringify(c.currentProcess)).not.toMatch(/8300|8400|75,--/);});
it("overdue source quote is withheld by actual mock tool execution",async()=>{vi.setSystemTime(new Date("2026-11-08T02:24:14.001Z"));const t=await tools();expect(JSON.stringify(await t.search_rules.execute!({query:"funding"},callContext))).not.toContain("11,904");});

it("known saved process reminders cannot leak obsolete payable prose to model tools",async()=>{mocks.listTasks.mockResolvedValue([{task_key:"rule:"+id+":step:41",title:"OLD 8400 INR payable",description:"OLD quote 8300 inr",source_url:"https://india.diplo.de/",due_date:null,done:false}]);const t=await tools();const r=await t.get_user_context.execute!({},callContext) as {tasks:unknown;whereTheUserIs:unknown};expect(JSON.stringify(r.tasks)).not.toMatch(/8400|8300/);expect(JSON.stringify(r.whereTheUserIs)).not.toMatch(/8400|8300/);expect(JSON.stringify(r.tasks)).toContain("personal history");});
