import type { SavedCourse } from "@/lib/saved-courses"

export const mockSavedCourses: SavedCourse[] = [
  {
    id: "mock-applied-ai",
    name: "Applied Artificial Intelligence",
    university: "Sample University of Applied Sciences",
    city: "Ingolstadt",
    language: "English",
    semester: "Winter",
    deadline: "2027-05-02",
    applicationRoute: "University portal",
    admissionType: "NC-free",
    status: "Almost ready",
    readiness: 90,
    missingItems: ["Final transcript"],
  },
  {
    id: "mock-business",
    name: "International Business",
    university: "Sample University Berlin",
    city: "Berlin",
    language: "English",
    semester: "Winter",
    deadline: "2027-06-30",
    applicationRoute: "uni-assist",
    admissionType: "Restricted admission",
    status: "In progress",
    readiness: 65,
    missingItems: ["Certified transcript", "Language certificate"],
  },
  {
    id: "mock-computer-science",
    name: "Computer Science",
    university: "Sample Technical University",
    city: "Munich",
    language: "German / English",
    semester: "Winter",
    deadline: "2027-07-15",
    applicationRoute: "University portal",
    admissionType: "Aptitude assessment",
    status: "Needs review",
    readiness: 50,
    missingItems: ["APS verification", "German B2", "Module description"],
  },
]
