// Ship 1 target countries. Qualification strings MUST match the
// recognition_rules / grade_conversion data in lib/seed-data.js.
export const COUNTRIES = [
  "India",
  "Pakistan",
  "China",
  "Malaysia",
  "Saudi Arabia",
  "UAE",
  "Kuwait",
  "Other / Not listed",
];

// International qualifications anyone can hold regardless of country.
// Appended to every country's list below. Recognition for these is matched by
// a country-agnostic rule (country 'Any') in lib/seed-data.js.
export const UNIVERSAL_QUALIFICATIONS = [
  "GCE A-Levels",
  "IB Diploma",
  "Studienkolleg (completed)",
];

const COUNTRY_QUALIFICATIONS = {
  India: [
    "Standard 12th (CBSE/ICSE/State Board)",
    "Indian Bachelor's (recognised university, subject match)",
    "JEE Advanced (qualified)",
  ],
  Pakistan: [
    "HSSC / Intermediate",
    "Pakistani Bachelor's (recognised university)",
  ],
  China: ["Gaokao"],
  Malaysia: [
    "STPM (with SPM)",
    "UEC / Matriculation / Foundation / Diploma",
  ],
  "Saudi Arabia": ["Thanawiya Amma / US-system school"],
  UAE: ["Thanawiya (secondary certificate)"],
  Kuwait: ["Shahadat Al-Thanawiya Al-Amma"],
  "Other / Not listed": ["Any"],
};

// Every country also offers the universal A-Levels / IB routes.
export const QUALIFICATIONS_BY_COUNTRY = Object.fromEntries(
  Object.entries(COUNTRY_QUALIFICATIONS).map(([country, quals]) => [
    country,
    [...quals, ...UNIVERSAL_QUALIFICATIONS],
  ])
);

export const GRADING_SCALES = [
  "Percentage (0–100)",
  "CGPA out of 10",
  "CGPA out of 4",
  "German scale (1.0–6.0)",
  "IB points (0–45)",
  "A-Level grades",
];

export const LANGUAGE_CERTS = ["IELTS", "TOEFL (iBT)", "TestDaF", "DSH", "None / planning to take"];

// The certificate types a user can add (the per-cert status replaces the old
// "None / planning to take" pseudo-option).
export const LANGUAGE_TEST_OPTIONS = ["IELTS", "TOEFL (iBT)", "TestDaF", "DSH"];

export const UNIVERSITIES = [
  {
    id: "tum",
    name: "Technical University of Munich",
    short: "TUM",
    city: "Munich",
    state: "Bavaria",
    portalType: "TUMonline (direct)",
    generalDeadlines: "Winter: 15 Jul · Summer: 15 Jan",
    semesterContribution: "€ 85 / semester",
    blurb: "Bavaria's flagship technical university with strong engineering, CS, and natural sciences programs.",
  },
  {
    id: "lmu",
    name: "Ludwig Maximilian University of Munich",
    short: "LMU",
    city: "Munich",
    state: "Bavaria",
    portalType: "uni-assist",
    generalDeadlines: "Winter: 15 Jul · Summer: 15 Jan",
    semesterContribution: "€ 85 / semester",
    blurb: "One of Europe's oldest and most comprehensive research universities — humanities, law, medicine, sciences.",
  },
  {
    id: "kit",
    name: "Karlsruhe Institute of Technology",
    short: "KIT",
    city: "Karlsruhe",
    state: "Baden-Württemberg",
    portalType: "KIT portal (direct)",
    generalDeadlines: "Winter: 15 Jul · Summer: 15 Jan",
    semesterContribution: "€ 171 / semester",
    blurb: "Merger of a university and a national research lab — strong in CS, engineering, and physics.",
  },
  {
    id: "tub",
    name: "Technical University of Berlin",
    short: "TU Berlin",
    city: "Berlin",
    state: "Berlin",
    portalType: "uni-assist",
    generalDeadlines: "Winter: 15 Jul · Summer: 15 Jan",
    semesterContribution: "€ 315 / semester",
    blurb: "Berlin's technical powerhouse — engineering, planning, and a vibrant startup-adjacent ecosystem.",
  },
  {
    id: "rwth",
    name: "RWTH Aachen University",
    short: "RWTH Aachen",
    city: "Aachen",
    state: "North Rhine-Westphalia",
    portalType: "uni-assist + RWTHonline",
    generalDeadlines: "Winter: 15 Jul · Summer: 15 Jan",
    semesterContribution: "€ 312 / semester",
    blurb: "Germany's largest technical university — global reputation in mechanical, electrical, and CS.",
  },
  {
    id: "freiburg",
    name: "University of Freiburg",
    short: "Uni Freiburg",
    city: "Freiburg im Breisgau",
    state: "Baden-Württemberg",
    portalType: "uni-assist",
    generalDeadlines: "Winter: 15 Jul · Summer: 15 Jan",
    semesterContribution: "€ 171 / semester",
    blurb: "Historic Black-Forest university with strong humanities, life sciences, and microsystems engineering.",
  },
  {
    id: "stuttgart",
    name: "University of Stuttgart",
    short: "Uni Stuttgart",
    city: "Stuttgart",
    state: "Baden-Württemberg",
    portalType: "C@MPUS (direct)",
    generalDeadlines: "Winter: 15 Jul · Summer: 15 Jan",
    semesterContribution: "€ 169 / semester",
    blurb: "Industry-linked engineering hub with automotive, aerospace, and production technology at its core.",
  },
  {
    id: "saar",
    name: "Saarland University",
    short: "Saarland",
    city: "Saarbrücken",
    state: "Saarland",
    portalType: "uni-assist",
    generalDeadlines: "Winter: 15 Jul · Summer: 15 Jan",
    semesterContribution: "€ 295 / semester",
    blurb: "Small, international campus — CS, bioinformatics, and European/cross-border studies stand out.",
  },
  {
    id: "tub_tue",
    name: "University of Tübingen",
    short: "Tübingen",
    city: "Tübingen",
    state: "Baden-Württemberg",
    portalType: "alma portal (direct)",
    generalDeadlines: "Winter: 15 Jul · Summer: 15 Jan",
    semesterContribution: "€ 166 / semester",
    blurb: "Classic research university with a strong Excellence-Strategy profile in ML, neuroscience, and theology.",
  },
  {
    id: "tud",
    name: "TU Darmstadt",
    short: "TU Darmstadt",
    city: "Darmstadt",
    state: "Hesse",
    portalType: "TUCaN (direct)",
    generalDeadlines: "Winter: 15 Jul · Summer: 15 Jan",
    semesterContribution: "€ 279 / semester",
    blurb: "Engineering-focused university in the Rhine-Main region with close ties to industry and ESA/DLR.",
  },
];

export const COURSES = [
  // TUM
  {
    id: "tum-cs",
    universityId: "tum",
    name: "Informatics (Computer Science)",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: false,
    ncValue: "1.8 (WS 2024/25)",
    admissionRequirements:
      "University entrance qualification recognized in Germany. Subject-specific aptitude (formal via grade average; not a separate test).",
    languageRequirements: "DSH-2, TestDaF 4×4, or equivalent German proof.",
    courseStructure:
      "6 semesters · 180 ECTS · Core CS (algorithms, systems, theory, software engineering) + electives + bachelor thesis.",
    howToApply: "TUMonline direct application. APS required for Indian/Chinese/Vietnamese applicants.",
    applicationDeadline: "15 July (Winter intake)",
    keywords: ["computer science", "informatics", "cs", "programming"],
    applyUrl: "#",
    summary: "Rigorous core-CS curriculum taught entirely in German — one of the most competitive in Bavaria.",
  },
  {
    id: "tum-mgt-tech",
    universityId: "tum",
    name: "Management & Technology",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: false,
    ncValue: "1.7 (WS 2024/25)",
    admissionRequirements: "HZB + subject-specific aptitude assessment (Eignungsfeststellung).",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure:
      "6 semesters · Business core (60 ECTS) + technical specialization in informatics, engineering, or natural sciences (60 ECTS) + electives + thesis.",
    howToApply: "TUMonline portal. Upload transcripts and CV; aptitude panel reviews applications.",
    applicationDeadline: "31 May (Winter intake)",
    keywords: ["management", "business", "technology", "engineering management"],
    applyUrl: "#",
    summary: "TUM's flagship business-with-tech program — half management, half technical depth.",
  },
  {
    id: "tum-mech",
    universityId: "tum",
    name: "Mechanical Engineering",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB recognized in Germany. No numerus clausus at present.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure:
      "6 semesters · Math, mechanics, thermodynamics, materials, design, control, electives, thesis.",
    howToApply: "TUMonline direct.",
    applicationDeadline: "15 July",
    keywords: ["mechanical", "engineering", "maschinenbau"],
    applyUrl: "#",
    summary: "Classic mechanical engineering curriculum at Germany's top engineering university.",
  },
  // LMU
  {
    id: "lmu-bwl",
    universityId: "lmu",
    name: "Business Administration (BWL)",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: false,
    ncValue: "2.1 (WS 2024/25)",
    admissionRequirements: "HZB + NC-based admission via local procedure.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure:
      "6 semesters · Accounting, finance, marketing, management, economics, methods, electives, thesis.",
    howToApply: "uni-assist preliminary review, then LMU portal.",
    applicationDeadline: "15 July",
    keywords: ["business", "bwl", "management", "administration"],
    applyUrl: "#",
    summary: "One of Germany's largest and most respected BWL programs.",
  },
  {
    id: "lmu-econ",
    universityId: "lmu",
    name: "Economics",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: false,
    ncValue: "2.3 (WS 2024/25)",
    admissionRequirements: "HZB + NC-based admission.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure: "6 semesters · Micro, macro, econometrics, policy electives, thesis.",
    howToApply: "uni-assist then LMU portal.",
    applicationDeadline: "15 July",
    keywords: ["economics", "vwl"],
    applyUrl: "#",
    summary: "Research-led economics program with strong quantitative emphasis.",
  },
  {
    id: "lmu-stats",
    universityId: "lmu",
    name: "Statistics & Data Science",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB. Open-admission for now; math pre-course recommended.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure: "6 semesters · Probability, inference, regression, ML, computing, applied project, thesis.",
    howToApply: "uni-assist then LMU portal.",
    applicationDeadline: "15 July",
    keywords: ["statistics", "data science", "ml", "analytics"],
    applyUrl: "#",
    summary: "A strong mathematical-statistics foundation paired with modern data-science electives.",
  },
  // KIT
  {
    id: "kit-cs",
    universityId: "kit",
    name: "Informatik (Computer Science)",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB recognized in Germany.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure:
      "6 semesters · 180 ECTS · Core CS, theoretical foundations, systems, practical labs, electives, thesis.",
    howToApply: "KIT portal direct after uni-assist preliminary check for non-EU applicants.",
    applicationDeadline: "15 July",
    keywords: ["computer science", "informatik", "cs"],
    applyUrl: "#",
    summary: "Deep, math-heavy informatics program — known for algorithms and systems rigor.",
  },
  {
    id: "kit-mech",
    universityId: "kit",
    name: "Mechanical Engineering",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB recognized in Germany.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure: "6 semesters · Engineering math, mechanics, design, thermo-fluid, control, thesis.",
    howToApply: "KIT portal direct.",
    applicationDeadline: "15 July",
    keywords: ["mechanical", "engineering", "maschinenbau"],
    applyUrl: "#",
    summary: "Breadth-first ME program with strong ties to automotive and energy industries.",
  },
  // TU Berlin
  {
    id: "tub-cs",
    universityId: "tub",
    name: "Computer Engineering (Technische Informatik)",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: false,
    ncValue: "2.4 (WS 2024/25)",
    admissionRequirements: "HZB + NC-based admission.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure: "6 semesters · Digital systems, OS, networks, embedded, electives, thesis.",
    howToApply: "uni-assist then TU Berlin portal.",
    applicationDeadline: "15 July",
    keywords: ["computer engineering", "technische informatik", "embedded"],
    applyUrl: "#",
    summary: "Hardware-adjacent CS program bridging electrical engineering and software.",
  },
  {
    id: "tub-ind",
    universityId: "tub",
    name: "Industrial Engineering & Management",
    degree: "B.Sc.",
    semester: "Both semesters",
    language: "German",
    ncFree: false,
    ncValue: "2.6 (WS 2024/25)",
    admissionRequirements: "HZB + NC-based admission.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure:
      "6 semesters · Engineering core + economics/management + specialization (construction, energy, IT, traffic, logistics).",
    howToApply: "uni-assist then TU Berlin portal.",
    applicationDeadline: "15 Jul / 15 Jan",
    keywords: ["industrial engineering", "wirtschaftsingenieur", "management"],
    applyUrl: "#",
    summary: "Wirtschaftsingenieurwesen — Germany's signature engineering-plus-business degree.",
  },
  // RWTH
  {
    id: "rwth-mech",
    universityId: "rwth",
    name: "Mechanical Engineering",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB. Self-Assessment recommended before enrolment.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure: "6 semesters · Math, mechanics, thermo-fluids, design, production, electives, thesis.",
    howToApply: "uni-assist then RWTHonline.",
    applicationDeadline: "15 July",
    keywords: ["mechanical", "engineering", "maschinenbau"],
    applyUrl: "#",
    summary: "One of the most respected ME programs in Europe — large cohort, strong industry pipeline.",
  },
  {
    id: "rwth-cs",
    universityId: "rwth",
    name: "Computer Science",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: false,
    ncValue: "2.2 (WS 2024/25)",
    admissionRequirements: "HZB + NC-based admission.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure: "6 semesters · Foundations, systems, theory, applications, electives, thesis.",
    howToApply: "uni-assist then RWTHonline.",
    applicationDeadline: "15 July",
    keywords: ["computer science", "informatik", "cs"],
    applyUrl: "#",
    summary: "Broad CS program with notable strengths in software engineering and HPC.",
  },
  // Freiburg
  {
    id: "frei-msc",
    universityId: "freiburg",
    name: "Microsystems Engineering",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "English",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB. Motivation letter reviewed for international applicants.",
    languageRequirements: "IELTS 6.5 / TOEFL iBT 95 or equivalent.",
    courseStructure: "6 semesters · Math/physics, electronics, MEMS, fabrication, labs, thesis.",
    howToApply: "uni-assist application.",
    applicationDeadline: "15 July",
    keywords: ["microsystems", "engineering", "mems", "electronics"],
    applyUrl: "#",
    summary: "Rare English-taught bachelor in Germany — micro/nano engineering with a strong research base.",
  },
  {
    id: "frei-libs",
    universityId: "freiburg",
    name: "Liberal Arts and Sciences",
    degree: "B.A./B.Sc.",
    semester: "Winter only",
    language: "English",
    ncFree: false,
    ncValue: "Portfolio + interview",
    admissionRequirements: "HZB + written application, essays, and admission interview.",
    languageRequirements: "IELTS 6.5 / TOEFL iBT 95.",
    courseStructure:
      "6 semesters · Interdisciplinary core + major track (Culture & History, Earth & Environmental, Life Sciences, Governance) + capstone.",
    howToApply: "UCF direct application portal.",
    applicationDeadline: "15 April",
    keywords: ["liberal arts", "interdisciplinary", "humanities"],
    applyUrl: "#",
    summary: "University College Freiburg — Germany's English-taught liberal-arts college model.",
  },
  // Stuttgart
  {
    id: "stu-aero",
    universityId: "stuttgart",
    name: "Aerospace Engineering",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB. Mandatory 8-week pre-study internship.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure: "6 semesters · Math, mechanics, propulsion, avionics, structures, electives, thesis.",
    howToApply: "C@MPUS portal (direct).",
    applicationDeadline: "15 July",
    keywords: ["aerospace", "aviation", "luft und raumfahrt"],
    applyUrl: "#",
    summary:
      "Stuttgart is one of three German universities offering a dedicated Luft- und Raumfahrttechnik bachelor.",
  },
  {
    id: "stu-auto",
    universityId: "stuttgart",
    name: "Automotive & Engine Technology",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB + 8-week pre-study internship.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure: "6 semesters · Engine technology, vehicle dynamics, electrification, production, thesis.",
    howToApply: "C@MPUS portal.",
    applicationDeadline: "15 July",
    keywords: ["automotive", "engine", "kraftfahrzeug"],
    applyUrl: "#",
    summary: "Deeply industry-linked program in Germany's automotive capital.",
  },
  // Saarland
  {
    id: "saar-cs",
    universityId: "saar",
    name: "Computer Science",
    degree: "B.Sc.",
    semester: "Both semesters",
    language: "English/German (mixed)",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB. English-track available with IELTS/TOEFL.",
    languageRequirements: "IELTS 6.5 or DSH-2.",
    courseStructure: "6 semesters · CS foundations, systems, theory, AI electives, seminar, thesis.",
    howToApply: "uni-assist application.",
    applicationDeadline: "15 Jul / 15 Jan",
    keywords: ["computer science", "cs", "informatics"],
    applyUrl: "#",
    summary: "Small, research-intensive CS program embedded with Max Planck and DFKI institutes.",
  },
  {
    id: "saar-bio",
    universityId: "saar",
    name: "Bioinformatics",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "English",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB + motivation letter.",
    languageRequirements: "IELTS 6.5 / TOEFL iBT 90.",
    courseStructure: "6 semesters · Bio foundations, CS foundations, algorithms for bio, lab rotations, thesis.",
    howToApply: "uni-assist application.",
    applicationDeadline: "15 July",
    keywords: ["bioinformatics", "computational biology", "biology"],
    applyUrl: "#",
    summary: "One of Germany's first bioinformatics programs — taught in English from day one.",
  },
  // Tübingen
  {
    id: "tue-cs",
    universityId: "tub_tue",
    name: "Computer Science",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB recognized in Germany.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure: "6 semesters · CS core, ML electives, systems, theory, thesis.",
    howToApply: "alma portal (direct).",
    applicationDeadline: "15 July",
    keywords: ["computer science", "informatik", "ml"],
    applyUrl: "#",
    summary: "Strong ML and cognitive-systems focus thanks to the Cluster of Excellence 'Machine Learning'.",
  },
  {
    id: "tue-cogsci",
    universityId: "tub_tue",
    name: "Cognitive Science",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: false,
    ncValue: "2.0 (WS 2024/25)",
    admissionRequirements: "HZB + NC-based admission.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure:
      "6 semesters · Interdisciplinary core (philosophy, linguistics, neuroscience, CS, psychology) + specialization + thesis.",
    howToApply: "alma portal.",
    applicationDeadline: "15 July",
    keywords: ["cognitive science", "neuroscience", "psychology"],
    applyUrl: "#",
    summary: "One of Germany's only dedicated cognitive-science bachelors.",
  },
  // Darmstadt
  {
    id: "tud-cs",
    universityId: "tud",
    name: "Computer Science",
    degree: "B.Sc.",
    semester: "Winter only",
    language: "German",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB. Orientation weeks in October.",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure: "6 semesters · Foundations, systems, theory, applied CS electives, thesis.",
    howToApply: "TUCaN portal (direct).",
    applicationDeadline: "15 July",
    keywords: ["computer science", "informatik"],
    applyUrl: "#",
    summary: "Widely ranked as one of Germany's strongest CS programs, with deep security and AI research.",
  },
  {
    id: "tud-ee",
    universityId: "tud",
    name: "Electrical Engineering & Information Technology",
    degree: "B.Sc.",
    semester: "Both semesters",
    language: "German",
    ncFree: true,
    ncValue: null,
    admissionRequirements: "HZB + 6-week pre-study internship (can be deferred).",
    languageRequirements: "DSH-2 or TestDaF 4×4.",
    courseStructure: "6 semesters · EE fundamentals, communications, power, electronics, thesis.",
    howToApply: "TUCaN portal.",
    applicationDeadline: "15 Jul / 15 Jan",
    keywords: ["electrical engineering", "ee", "elektrotechnik"],
    applyUrl: "#",
    summary: "Classic EE degree with a strong optional ESA/DLR-linked specialization track.",
  },
];
