// Source review 2026-10-08. Candidates remain unpublished; never imported by runtime.
import type { EngineRule } from '../lib/engine/evaluate';
const database = 'https://www.daad.de/en/studying-in-germany/requirements/admission-database/?ad-layer=6&ad-layerId=';
const scope = { target_degree: 'bachelor', curriculum: 'national', aps_issuer_country: 'pk', aps_qualification_context: 'national' } as const;
const metadata = { country: 'pk', status: 'draft', last_verified_at: '2026-10-07T23:15:59Z', published_at: null, applicability: 'Current DAAD undergraduate guidance; applicant reports; institution final assessment', effective_intake: null } as const;
const disclaimer = ' Subject-restricted preparatory/Feststellungsprüfung access only; no arbitrary programme eligibility or admission guarantee. Target family is applicant-reported, not independently verified. Current official database guidance is nonbinding; the institution makes the final assessment. Effective intake is not established.';
export const pakistanCandidates: (EngineRule & {
    country: string;
    published_at: null;
    applicability: string;
    effective_intake: null;
})[] = [];
for (const [group, families, label, prep] of [
    ['science', ['medicine', 'natural_sciences', 'technology'], 'Medicine, Natural Sciences and Technology', '193'],
    ['commerce', ['social_sciences', 'economics'], 'Social Sciences and Economics', '197'],
    ['humanities', ['humanities'], 'Humanities', '204'],
] as const) {
    pakistanCandidates.push({ ...metadata, id: 'pakistan-prep-' + group, conditions: { ...scope, pk_certificate: { op: 'in', value: ['hssc', 'intermediate'] }, pk_documentary_group: group, pk_school_completion: 'completed_12_grades', pk_grade_percent: { op: 'gte', value: 50 }, pk_prior_study_kind: 'none', pk_target_family: { op: 'in', value: [...families] } }, outcomes: { path: 'studienkolleg', note: 'Preparatory subject areas: ' + label + '.' + disclaimer }, source_url: database + prep, source_quote: group === 'humanities' ? 'subject area of Humanities' : label });

}
for (const [kind, note] of [['completed_qualification', 'Completed qualification outcomes (including two-/four-year degrees) require separate official assessment; degree completion is distinct from successful academic-year study.'], ['other', 'Another prior qualification requires its own official assessment.'], ['unknown', 'Prior university-study answer is missing or uncertain; elapsed time and a university name do not establish successful academic years.']] as const)
    pakistanCandidates.push({ ...metadata, id: 'pakistan-review-' + kind, conditions: { ...scope, pk_prior_study_kind: kind }, outcomes: { path: 'unknown', note: note + ' Confirm with the university and uni-assist Pakistan.' }, source_url: 'https://www.uni-assist.de/en/tools/info-country-by-country/details-country/country/pk/', source_quote: 'overview of subjects and grades' });
pakistanCandidates.push({ ...metadata, id: 'pakistan-master-review', conditions: { target_degree: 'master', certificate_country: 'pk' }, outcomes: { path: 'unknown', note: 'Pakistan master admission requires a separate completed-qualification assessment. Completed two-/four-year degrees and HEC attestation do not establish programme eligibility; confirm with the institution and uni-assist Pakistan. The two-year-degree discrepancy differs from the prior-study one-/two-year conflict.' }, source_url: 'https://www.uni-assist.de/en/tools/info-country-by-country/details-country/country/pk/', source_quote: 'minimum passing grade for your degree to be awarded' });

export const PAKISTAN_CURRENT_SOURCE = 'https://anabin.kmk.org/db/schulabschluesse-mit-hochschulzugang';
export const PAKISTAN_BROCHURE = 'https://www.daad.pk/files/2022/11/Study-in-Germany-Undergraduate-Degree-Courses_2022.pdf';
const currentScope = {...scope, pk_certificate:{op:'in' as const,value:['hssc','intermediate']}, pk_school_completion:'completed_12_grades',pk_grade_percent:{op:'gte' as const,value:50},pk_prior_study_kind:'bachelor',pk_prior_study_country:'pk',pk_prior_study_completion:'in_progress',pk_successful_academic_years:{op:'gte' as const,value:1},pk_study_mode:'full_time',pk_study_regulations:'confirmed',pk_annual_records:'confirmed',pk_reported_recognition:'reported_official_confirmed',pk_reported_target_relation:{op:'in' as const,value:['reported_official_previous','reported_official_closely_related']},pk_current_assessment:'reported_current_support',intake_index:{op:'in' as const,value:[4053,4054,4055]}};
const currentMetadata={...metadata,last_verified_at:'2026-10-08T01:24:33Z',applicability:'Reviewed current product intakes 4053/4054/4055; not source commencement. Ongoing Bachelor is a conservative product subset, not an official completion requirement.'};
const currentNote='Current anabin academic access orientation: direct subject-restricted access to the previous university subject and neighbouring/related subjects, at all higher education institutions (institution-type scope, not all programmes). Applicant-reported recognition, successful academic year and target relationship are not verified by the app. The still-linked regional DAAD brochure states two successful years: '+PAKISTAN_BROCHURE+'. No formal withdrawal, legal precedence or historical commencement is established. Confirm this applicable assessment with the intended institution/uni-assist; the institution makes the final decision. Current intake enumeration is product coverage, not a source effective date. Ongoing Bachelor is a conservative product subset; completed qualifications and Master require separate assessment.';
for(const [group,entry,corroboration] of [['science','PAK-BV03','195'],['commerce','PAK-BV02','199'],['humanities','PAK-BV01',null]] as const){
 const conditions={...currentScope,pk_documentary_group:group};
 pakistanCandidates.push({...currentMetadata,id:'pakistan-current-year-'+group,conditions,outcomes:{path:'subject_restricted',steps:[{order:1,text:'Confirm the reported qualification, successful study and previous/neighbouring target assessment with the intended institution/uni-assist; review the linked regional brochure discrepancy.'}],note:entry+'. '+currentNote+(corroboration?' Corroborating DAAD result: '+database+corroboration: ' DAAD206 retrieval failure is not contrary evidence.')},source_url:PAKISTAN_CURRENT_SOURCE,source_quote:'bei Nachweis von 1 erfolgreichen Studienjahr(en) — Das nachzuweisende Studienjahr muss an einer anerkannten Hochschule in einem wissenschaftlichen Studiengang absolviert worden sein.'});
 // Evidence-only discrepancy disclosure: no competing executable admission path.
 pakistanCandidates.push({...currentMetadata,id:'pakistan-current-brochure-'+group,conditions,outcomes:{note:'Disclosed regional summary discrepancy: FSc + two successfully completed years. '+currentNote},source_url:PAKISTAN_BROCHURE,source_quote:'FSc + two successfully completed years'});
}
pakistanCandidates.push({...currentMetadata,id:'pakistan-study-evidence-review',conditions:{...scope,pk_prior_study_kind:'bachelor'},outcomes:{path:'unknown',note:'Pakistan current one-year coverage requires completed twelve-grade HSSC/Intermediate, documentary group, overall percentage, one successful Pakistan academic Bachelor year, full-time study under regulations, annual records and separate applicable reported success/recognition/previous-or-neighbouring-target references plus current institutional assessment. Missing, historical/noncovered intake or irregular/discontinued/foreign study needs individual confirmation. A specific contrary applicable institutional assessment is an individual confirmation conflict. Below 50 only this formula is unmet; completed qualifications are separate.'},source_url:PAKISTAN_CURRENT_SOURCE,source_quote:'bei Nachweis von 1 erfolgreichen Studienjahr(en)'});
