// Reviewed 2026-10-08; candidates only. No seed/publication/DB operation.
import type { EngineRule } from "../lib/engine/evaluate";
import { SAUDI_SOURCE, SAUDI_SOURCE_DE, SAUDI_ANABIN, NATIONAL_CATEGORIES, SCIENCE_STREAMS } from "../lib/engine/saudi";
const scope = { target_degree: "bachelor", curriculum: "national", aps_issuer_country: "sa", aps_qualification_context: "national", sa_certificate_evidence: "v2", intake_index: { op: "in", value: [4053,4054,4055] as number[] } } as const;
const study = { sa_prior_study_kind: "bachelor", sa_reported_recognition: "confirmed", sa_reported_target_relation: {op:"in",value:["previous","neighbouring"] as string[]} } as const;
const evidence = { country: "sa", status: "draft", published_at: null, last_verified_at: "2026-10-08T00:00:00Z" } as const;
const report = "Current product intake coverage is exactly Winter 2026/27, Summer 2027 and Winter 2027/28; verification is not source commencement. Based on applicant-reported applicable official assessments; UniPirate has not independently verified these reports. The university decides programme admission.";
const privateScope = { ...scope, sa_certificate_subtype: "private_school", sa_reported_subject_assessment: "met", sa_private_assessment_coverage: "met", ...study } as const;
const industrialScope = { ...scope, sa_certificate_subtype: { op: "in", value: ["industrial_certificate", "industrial_diploma"] as string[] }, sa_certificate_evidence: {op:"in",value:["v1","v2"] as string[]} } as const;
export const saudiCandidates: (EngineRule & { country: string; published_at: null })[] = [
  { ...evidence, id: "sa-reviewed-private-one", conditions: { ...privateScope, sa_reported_target_relation: "previous", sa_successful_bachelor_years: 1 },
    outcomes: { path: "studienkolleg", note: "SAU-BV05 private-school diploma: preparatory study in the previous subject area at all higher education institutions. Applicable regional-US accreditation, subject breadth and all individual passing minima are covered by the reported official assessment; Anabin " + SAUDI_ANABIN + ". " + report,
      steps: [{ order: 15, text: "Confirm Studienkolleg in the previous subject area with the university using your private-school subject assessment and successful Bachelor-year records." }] },
    source_url: SAUDI_SOURCE_DE, source_quote: "in einem Bachelor-Studium an einer anerkannten Hochschule erfolgreich abgeschlossen" },
  { ...evidence, id: "sa-reviewed-private-two", conditions: { ...privateScope, sa_successful_bachelor_years: { op: "gte", value: 2 } },
    outcomes: { path: "subject_restricted", note: "SAU-BV05 private-school diploma: Bachelor access in the previous or neighbouring subject area at all higher education institutions. Applicable accreditation, breadth, individual minima and neighbouring-subject scope follow Anabin " + SAUDI_ANABIN + ". " + report,
      steps: [{ order: 15, text: "Confirm Bachelor admission in the previous or neighbouring subject area using your private-school subject assessment and successful two-year Bachelor-study records." }] },
    source_url: SAUDI_SOURCE, source_quote: "Successful completion of two years of studies" },
  { ...evidence, id: "sa-reviewed-industrial-enrollment", conditions: { ...industrialScope, sa_prior_study_kind: "bachelor", sa_reported_recognition: "confirmed", sa_reported_enrollment: "document", sa_reported_enrollment_relation: "previous" },
    outcomes: { path: "studienkolleg", institution_restriction: "fachhochschule", note: "Industrial school certificate: preparatory study at a Fachhochschule in the enrollment subject area, from Winter 2026/27. " + report,
      steps: [{ order: 15, text: "Confirm Studienkolleg at a Fachhochschule (university of applied sciences) in the subject area on your recognized Bachelor enrollment certificate." }] },
    source_url: SAUDI_SOURCE, source_quote: "From the 2026/27 winter semester onwards" },
  { ...evidence, id: "sa-reviewed-industrial-year", conditions: { ...industrialScope, ...study, target_field: { op: "neq", value: "" }, sa_successful_bachelor_years: { op: "gte", value: 1 } },
    outcomes: { path: "subject_restricted", institution_restriction: "fachhochschule", note: "Industrial school certificate: Bachelor access only at a Fachhochschule in the previous or neighbouring subject area, from Winter 2026/27. Anabin SAU-BV6 specifies institution scope; uni-assist " + SAUDI_SOURCE_DE + " supplies the Winter 2026/27 regime. " + report,
      steps: [{ order: 15, text: "Confirm Bachelor admission at a Fachhochschule in the previous or neighbouring subject area using your industrial school certificate and successful Bachelor-year records." }] },
    source_url: SAUDI_ANABIN, source_quote: "Direkter Zugang (fachorientiert)\nfür die bisherige Fachrichtung und benachbarte Fächer\nbei Nachweis von 1 erfolgreichen Studienjahr(en)\nnur zu Fachhochschulen" },
  ...([ {id:"literary", entry:"SAU-BV01", streams:["Literary Section","Literary Track","Human Sciences Section"], families:["humanities","law","social_sciences","economics"]}, {id:"science", entry:"SAU-BV02", streams:SCIENCE_STREAMS, families:[]}, {id:"commercial", entry:"SAU-BV03", streams:["Commercial Section"], families:["economics"]} ]).flatMap(n => {
    const national = {...scope, sa_certificate_subtype:"national", sa_secondary_completion:"completed_12_year_secondary", sa_national_category:{op:"in" as const,value:NATIONAL_CATEGORIES}, sa_national_stream:{op:"in" as const,value:n.streams}};
    const boundary = " Covered product scope uses a reported completed twelve-grade category and recognized successful academic Bachelor history; these narrower reports are not additional national source prerequisites. " + report;
    return [
      {...evidence,id:"sa-reviewed-national-"+n.id+"-prep",conditions:{...national,...(n.families.length ? {sa_reported_target_family:{op:"in" as const,value:n.families}} : {})},outcomes:{path:"studienkolleg" as const,note:n.entry+": preparation "+(n.families.length?n.families.join(" / "):"in all Schwerpunktkurse")+" at all higher education institutions."+boundary,steps:[{order:15,text:"Confirm the applicable "+n.entry+" preparatory course with the admitting institution using your documentary certificate"+(n.families.length?" and applicable target classification":" (all Schwerpunktkurse)")+"."}]},source_url:SAUDI_ANABIN,source_quote:n.id==="science"?"Feststellungsprüfung/Studienkolleg (für alle Schwerpunktkurse)":"zu allen Hochschulen"},
      {...evidence,id:"sa-reviewed-national-"+n.id+"-year",conditions:{...national,...study,sa_successful_bachelor_years:{op:"gte" as const,value:1}},outcomes:{path:"subject_restricted" as const,note:n.entry+": direct undergraduate access in the previous or neighbouring study area at all higher education institutions."+boundary,steps:[{order:15,text:"Confirm direct Bachelor admission in the previous or neighbouring study area using the recognized successful academic year and applicable target relationship assessment."}]},source_url:SAUDI_ANABIN,source_quote:"bei Nachweis von 1 erfolgreichen Studienjahr(en)\nzu allen Hochschulen"},
    ];
  }),
  {...evidence,id:"sa-reviewed-completed-bachelor",conditions:{target_degree:"bachelor",intake_index:{op:"in",value:[4053,4054,4055]},sa_degree_evidence:"v2",sa_degree_issuer:"sa",sa_degree_context:"national",sa_degree_kind:"bachelor",sa_degree_completion:"completed",sa_degree_nominal_years:{op:"gte",value:4},sa_degree_mode:"regular",sa_degree_norms:"met",sa_degree_recognition:"confirmed",sa_degree_institution:"reported",sa_degree_field:"reported"},outcomes:{path:"direct",note:"SAU-BV BACHELOR: general undergraduate academic access to all subjects and higher education institutions for the reported recognized completed minimum-four-year Bachelor actually undertaken under prescribed norms and generally full time. This does not establish Master's equivalence. "+report,steps:[{order:15,text:"Confirm general undergraduate access with the university using the applicable official completed Bachelor qualification and recognition assessments; check separate programme requirements."}]},source_url:SAUDI_ANABIN,source_quote:"Bachelor"},
];
