import { describe, expect, it } from 'vitest';
import { deriveFacts, EngineRuleSchema, evaluate, type Profile } from '../evaluate';
import { ruleData } from '@/scripts/rules.bootstrap';
const rules = () => ruleData.filter(r => r.id.startsWith('pakistan-')).map(r => ({ ...r, status: 'verified' }));
export const pk: Profile = { targetDegree: 'bachelor', curriculumType: 'national', certificateCountry: 'pk', schoolQualification: { country: 'pk', context: 'national' }, schoolGradePercent: 50, targetField: 'cs', qualificationHistory: { hasPriorUniversityStudy: false }, pakistan: { version: 1, certificate: 'hssc', group: 'science', completion: 'completed_12_grades', targetFamily: 'technology', targetFamilyReference: 'University programme lists Technology' } };
describe('UP-ELIG-08 bounded Pakistan routes', () => {
    it.each([['science', 'technology', 'Medicine, Natural Sciences and Technology', '193'], ['commerce', 'economics', 'Social Sciences and Economics', '197'], ['humanities', 'humanities', 'Humanities', '204']])('verified prep %s', (group, targetFamily, family, id) => { const r = evaluate({ ...pk, pakistan: { ...pk.pakistan!, group: group as never, targetFamily: targetFamily as never } }, rules()); expect(r.path).toBe('studienkolleg'); expect(r.citations.find(c => c.supports.includes('path'))?.claim).toContain(family); expect(r.citations.map(c => c.sourceUrl)).toContain('https://www.daad.de/en/studying-in-germany/requirements/admission-database/?ad-layer=6&ad-layerId=' + id); });
    it('uses literal 49.99/50 and distinguishes missing', () => { expect(evaluate(pk, rules()).path).toBe('studienkolleg'); for (const n of [49.99, undefined]) {
        const r = evaluate({ ...pk, schoolGradePercent: n }, rules());
        expect(r.path).toBe('unknown');
        expect(r.unknowns.join(' ')).toMatch(n === undefined ? /percentage.*missing/i : /50%.*unmet/i);
    } });
    it.each([{ certificate: 'ssc' }, { certificate: 'fsc' }, { certificate: 'fa' }, { certificate: 'icom' }, { certificate: 'ics' }, { group: 'mixed' }, { group: 'other' }, { group: 'unknown' }, { completion: 'incomplete' }, { completion: 'unknown' }, { targetFamily: 'economics' }, { targetFamily: undefined }, { targetFamilyReference: '' }])('never broadens certificate/group/target %j', change => { expect(evaluate({ ...pk, pakistan: { ...pk.pakistan!, ...change } as never }, rules()).path).toBe('unknown'); });
    it.each([{ schoolQualification: undefined }, { schoolQualification: { country: 'in', context: 'national' } }, { schoolQualification: { country: 'pk', context: 'international' } }, { qualificationHistory: undefined }, { pakistan: undefined }, { targetDegree: 'master' }, { curriculumType: 'gce' }, { curriculumType: 'ib' }])('scope or missing evidence %j', change => { expect(evaluate({ ...pk, ...change } as Profile, rules()).path).toBe('unknown'); });
    it.each([0, .5, 1, 2])('successful years %s never activate disputed direct entry', completedYears => { const p = { ...pk, qualificationHistory: { hasPriorUniversityStudy: true, qualificationType: 'bachelor', institution: 'HEC name', country: 'pk', field: 'cs', degreeYears: 4, completedYears, completion: 'in_progress', pakistanStudy: { mode: 'full_time', regulations: 'confirmed', annualRecords: 'confirmed', successfulYearsReference: 'Annual marks attest attained years', recognition: 'reported_official_confirmed', recognitionReference: 'University assessment recognises institution and academic study', relation: 'reported_official_previous', relationReference: 'University assessment covers previous field and target' } } } as Profile; const r = evaluate(p, rules()); expect(r.path).toBe('unknown'); expect(deriveFacts(p).pk_successful_academic_years).toBe(completedYears); expect(r.unknowns.join(' ')).toMatch(/one.*two.*conflict/i); expect(r.citations.map(c => c.sourceUrl)).toEqual(expect.arrayContaining(['https://www.daad.de/en/studying-in-germany/requirements/admission-database/?ad-layer=6&ad-layerId=195', 'https://www.daad.pk/files/2022/11/Study-in-Germany-Undergraduate-Degree-Courses_2022.pdf'])); });
    it('keeps completed degree distinct and legacy generic keys inactive', () => { const p = { ...pk, qualificationHistory: { hasPriorUniversityStudy: true, qualificationType: 'bachelor', degreeYears: 2, completedYears: 2, completion: 'completed' } } as Profile; expect(evaluate(p, rules()).path).toBe('unknown'); expect(evaluate(p, rules()).unknowns.join(' ')).toMatch(/completed qualification/i); for (const key of ['years_of_university_study', 'prior_degree_years', 'university_study_institution_recognized'])
        expect(EngineRuleSchema.safeParse({ ...rules()[0], conditions: { [key]: 1 } }).success).toBe(false); });
    it('validates direct reports and never infers successful years from elapsed duration', () => { const p = { ...pk, qualificationHistory: { hasPriorUniversityStudy: true, qualificationType: 'bachelor', degreeYears: 4, completedYears: 1, completion: 'in_progress' } } as Profile; expect(deriveFacts(p).pk_successful_academic_years).toBeUndefined(); expect(deriveFacts({ ...pk, pakistan: { ...pk.pakistan!, version: 2 } as never }).pk_certificate).toBeUndefined(); });
    it('drafts malformed and equal-specificity disagreement remain honest', () => { const candidates = ruleData.filter(r => r.id.startsWith('pakistan-')); expect(candidates.length).toBeGreaterThan(2); expect(candidates.every(r => r.status === 'draft')).toBe(true); expect(evaluate(pk, candidates).path).toBe('unknown'); const good = rules()[0]; expect(evaluate(pk, [{ ...good, conditions: { typo: true } }]).path).toBe('unknown'); const r = evaluate(pk, [good, { ...good, id: 'opposed', outcomes: { path: 'direct' } }]); expect(r.path).toBe('unknown'); expect(r.citations.map(c => c.ruleId)).toContain('opposed'); });
    it('passport visa and intake do not change academic scope', () => { for (const nationality of ['in', 'pk', 'sa'])
        for (const visaApplicationCountry of ['in', 'pk', 'sa'])
            expect(evaluate({ ...pk, nationality, visaApplicationCountry, intake: { term: 'winter', year: 2025 } }, rules()).path).toBe('studienkolleg'); });
});
it.each(['medicine', 'natural_sciences', 'technology'])('Science supports only cited family %s', targetFamily => { const r = evaluate({ ...pk, pakistan: { ...pk.pakistan!, targetFamily: targetFamily as never } }, rules()); expect(r.path).toBe('studienkolleg'); });
it.each(['social_sciences', 'economics'])('Commerce supports cited family %s', targetFamily => expect(evaluate({ ...pk, pakistan: { ...pk.pakistan!, group: 'commerce', targetFamily: targetFamily as never } }, rules()).path).toBe('studienkolleg'));
it('Intermediate requires its own explicit category report', () => expect(evaluate({ ...pk, pakistan: { ...pk.pakistan!, certificate: 'intermediate' } }, rules()).path).toBe('studienkolleg'));
it.each(['group', 'certificate', 'completion'])('missing Pakistan %s is a targeted gap', key => { const r = evaluate({ ...pk, pakistan: { ...pk.pakistan!, [key]: undefined } }, rules()); expect(r.path).toBe('unknown'); expect(r.unknowns.join(' ')).toMatch(/missing or uncertain/); });
it.each(['part_time', 'distance_online', 'other', undefined])('study mode %s remains targeted unknown', mode => { const h = { hasPriorUniversityStudy: true, qualificationType: 'bachelor', institution: 'Reported university', country: 'pk', field: 'cs', completedYears: 1, completion: 'in_progress', pakistanStudy: { mode, annualRecords: 'confirmed', successfulYearsReference: 'Annual marks' } }; const r = evaluate({ ...pk, qualificationHistory: h as never }, rules()); expect(r.path).toBe('unknown'); expect(r.unknowns.join(' ')).toMatch(/full-time/); });
it.each(['in', 'other', 'unknown', undefined])('previous study country %s remains unknown', country => { const r = evaluate({ ...pk, qualificationHistory: { hasPriorUniversityStudy: true, qualificationType: 'bachelor', country, completedYears: 1, completion: 'in_progress' } }, rules()); expect(r.path).toBe('unknown'); expect(r.unknowns.join(' ')).toMatch(/Pakistan study country/); });
it.each(['completed', 'discontinued'])('irregular or completed history %s stays distinct', completion => { for (const degreeYears of [2, 4])
    expect(evaluate({ ...pk, qualificationHistory: { hasPriorUniversityStudy: true, qualificationType: 'bachelor', degreeYears, completedYears: 1, completion: completion as never } }, rules()).path).toBe('unknown'); });
it.each([{ annualRecords: 'unknown', successfulYearsReference: 'Two semesters' }, { annualRecords: 'confirmed', successfulYearsReference: undefined }, { annualRecords: 'confirmed', successfulYearsReference: ' ' }, { annualRecords: 'confirmed', successfulYearsReference: 'Yearly marks', mode: 'made_up' }])('invalid or insufficient year evidence %j is not attainment', pakistanStudy => { expect(deriveFacts({ ...pk, qualificationHistory: { hasPriorUniversityStudy: true, qualificationType: 'bachelor', completedYears: 1, pakistanStudy: pakistanStudy as never } }).pk_successful_academic_years).toBeUndefined(); });
it('recognition and relatedness require applicable references, not matching names', () => { const h = { hasPriorUniversityStudy: true, qualificationType: 'bachelor', institution: 'HEC attested University', field: 'cs', completedYears: 1, pakistanStudy: { recognition: 'reported_official_confirmed', relation: 'reported_official_previous' } } as const; const f = deriveFacts({ ...pk, qualificationHistory: h }); expect(f.pk_reported_recognition).toBe('unknown'); expect(f.pk_reported_target_relation).toBe('unknown'); });
it('Pakistan semantic keys cannot activate for India GCE IB or master', () => { for (const change of [{ targetDegree: 'master' }, { curriculumType: 'gce' }, { curriculumType: 'ib' }, { schoolQualification: { country: 'in', context: 'national' } }])
    expect(Object.keys(deriveFacts({ ...pk, ...change } as Profile)).filter(k => k.startsWith('pk_'))).toEqual([]); });
it('outside Commerce scope names target scope rather than changing the reported group', () => { const r = evaluate({ ...pk, pakistan: { ...pk.pakistan!, group: 'commerce', targetFamily: 'technology' } }, rules()); expect(r.unknowns.join(' ')).toMatch(/outside the preparatory subject scope/); expect(r.unknowns.join(' ')).not.toMatch(/documentary.*does not meet/); });
it('Pakistan master remains a targeted separate qualification assessment', () => { const r = evaluate({ ...pk, targetDegree: 'master', tertiaryQualification: { issuer: 'Example university', country: 'pk', context: 'national' }, qualificationHistory: { hasPriorUniversityStudy: true, qualificationType: 'bachelor', degreeYears: 4, completion: 'completed' } }, rules()); expect(r.path).toBe('unknown'); expect(r.unknowns.join(' ')).toMatch(/master.*qualification assessment/i); expect(r.citations.map(c => c.sourceUrl)).toContain('https://www.uni-assist.de/en/tools/info-country-by-country/details-country/country/pk/'); });
it('malformed direct-call history cannot create semantic successful-year evidence', () => { const p = { ...pk, qualificationHistory: { hasPriorUniversityStudy: true, qualificationType: 'bachelor', country: 'invalid-country', completedYears: 1, pakistanStudy: { annualRecords: 'confirmed', successfulYearsReference: 'Yearly marks' } } }; expect(deriveFacts(p as Profile).pk_successful_academic_years).toBeUndefined(); });
