import { ruleToChunk } from "@/lib/ai/kb";
import { describe, expect, it } from "vitest";
import { evaluate, type Profile } from "../evaluate";
import { saudiCandidates } from "@/scripts/saudi.rules";
import { saudiProfile, industrialProfile, completedSaudiProfile } from "./saudi.fixture";
const rules = () => saudiCandidates.map(r => ({...r, status: "verified" as const}));
const national = (stream: string, years = 0): Profile => ({...saudiProfile, saudiCertificate: {version: 2, subtype: "national", nationalCategory: "general_certificate", secondaryCompletion: "completed_12_year_secondary", nationalStream: stream, targetFamily: "reported_official_economics", targetFamilyReference: "Synthetic applicable classification for this exact target"}, qualificationHistory: {...saudiProfile.qualificationHistory!, completedYears: years}});
describe("current Saudi source contract", () => {
 it.each(["Literary Section", "Science Section", "Commercial Section"])("%s preparation and successful-year direct", stream => {
   expect(evaluate(national(stream),rules()).path).toBe("studienkolleg");
   expect(evaluate(national(stream,1),rules()).path).toBe("subject_restricted");
 });
 it("scientific preparation needs no narrow family", () => {const p=national("Scientific Track");p.saudiCertificate!.targetFamily=undefined;p.saudiCertificate!.targetFamilyReference=undefined;expect(evaluate(p,rules()).path).toBe("studienkolleg");});
 it("industrial successful study retains FH and removes preparation tasks", () => {const p={...industrialProfile,qualificationHistory:{...industrialProfile.qualificationHistory!,completedYears:1}};const r=evaluate(p,rules());expect(r).toMatchObject({path:"subject_restricted",institutionRestriction:"fachhochschule"});expect(r.stepsDetailed.map(s=>s.text).join(" ")).not.toMatch(/Studienkolleg/);});
 it("independent completed four-year degree grants general undergraduate access", () => {const p:Profile={...national("Science Section",4),saudiCertificate:undefined,curriculumType:"other",qualificationHistory:{...saudiProfile.qualificationHistory!,completion:"completed",completedYears:4,saudiBachelorEvidence:{version:2,context:"national",assessment:"reported_official_norms_full_time",reference:"Synthetic official exact Bachelor qualification assessment"}}};expect(evaluate(p,rules()).path).toBe("direct");});
 it("old private generic subject report does not certify new accreditation/minima",()=>{expect(evaluate({...saudiProfile,saudiCertificate:{...saudiProfile.saudiCertificate!,version:1,privateAssessmentCoverage:undefined}},rules()).path).toBe("unknown");});
 it.each(["reported_official_humanities","reported_official_law","reported_official_social_sciences","reported_official_economics"] as const)("literary applicable %s",targetFamily=>{const p=national("Literary Track");p.saudiCertificate!.targetFamily=targetFamily;expect(evaluate(p,rules()).path).toBe("studienkolleg");});
 it("national direct relation uses prior study, independently of prep family",()=>{const p=national("Commercial Section",1);p.saudiCertificate!.targetFamily="reported_official_outside";p.qualificationHistory!.priorStudyTargetRelation="reported_official_closely_related";expect(evaluate(p,rules()).path).toBe("subject_restricted");});
 it.each([undefined," ","x".repeat(501)])("restricted prep needs bounded reference %j",targetFamilyReference=>{const p=national("Literary Section");p.saudiCertificate!.targetFamilyReference=targetFamilyReference;expect(evaluate(p,rules()).path).toBe("unknown");});
 it("unsupported named stream and incomplete/category missing do not authorize preparation",()=>{for(const change of [{nationalStream:"science"},{nationalCategory:undefined},{secondaryCompletion:undefined}]){const p=national("Science Section");Object.assign(p.saudiCertificate!,change);expect(evaluate(p,rules()).path).toBe("unknown");}});
 it("private neighbouring direct requires two successful years and current coverage",()=>{const p={...saudiProfile,qualificationHistory:{...saudiProfile.qualificationHistory!,completedYears:2,priorStudyTargetRelation:"reported_official_closely_related" as const}};expect(evaluate(p,rules()).path).toBe("subject_restricted");for(const intake of [undefined,{term:"winter" as const,year:2028}])expect(evaluate({...p,intake},rules()).path).toBe("unknown");});
 it("degree evidence requires actual identity/norms/mode/recognition, never elapsed years or Master target",()=>{for(const change of [{degreeYears:2},{completion:"in_progress" as const},{priorStudyMode:"distance_online" as const},{priorStudyRecognitionReference:" "},{saudiBachelorEvidence:{...completedSaudiProfile.qualificationHistory!.saudiBachelorEvidence!,reference:" "}}])expect(evaluate({...completedSaudiProfile,qualificationHistory:{...completedSaudiProfile.qualificationHistory!,...change}},rules()).path).toBe("unknown");expect(evaluate({...completedSaudiProfile,targetDegree:"master"},rules()).path).toBe("unknown");});
 it("true equal-specificity incompatible scoped grants remain cited unknown",()=>{const direct=rules().find(r=>r.id==="sa-reviewed-national-science-year")!;const prep={...direct,id:"synthetic-scoped-conflict",outcomes:{...direct.outcomes,path:"studienkolleg" as const}};const r=evaluate(national("Science Section",1),[direct,prep]);expect(r.path).toBe("unknown");expect(r.citations.filter(c=>c.supports.includes("path"))).toHaveLength(2);});
 it("current KB and engine reject exclusion-only or missing family/category/intake scope",()=>{const p=national("Literary Section");const original=rules().find(r=>r.id==="sa-reviewed-national-literary-prep")!;for(const key of ["aps_issuer_country","sa_national_category","sa_reported_target_family","intake_index"]){const conditions={...original.conditions};delete conditions[key as keyof typeof conditions];const unsafe={...original,conditions};expect(evaluate(p,[unsafe]).path).toBe("unknown");expect(ruleToChunk({...unsafe,slug:unsafe.id,country_code:"sa",last_verified_at:unsafe.last_verified_at!}).content).toMatch(/unknown/);}const unsafe={...original,conditions:{...original.conditions,sa_reported_target_family:{op:"nin" as const,value:["outside"]}}};expect(evaluate(p,[unsafe]).path).toBe("unknown");});
});
