"use client";
import {withProcessContext,type PartialAnswers} from "./steps";
export function ProcessContextEditor({answers,onChange}:{answers:PartialAnswers;onChange:(next:PartialAnswers)=>void}) {
 const c=answers.processContext;
 const select=(key:keyof NonNullable<typeof c>,options:readonly [string,string][]) => <label>{key==="kind"?"Guidance to check":key==="purpose"?"Reported visa purpose":key==="mission"?"Reported responsible mission":key==="ageBracket"?"Reported age bracket":key==="exception"?"Reported fee/funding exception uncertainty":"Reported funding method"}<select value={typeof c?.[key]==="string"?c[key]:""} onChange={e=>onChange(withProcessContext(answers,key,(e.target.value||undefined) as never))}><option value="">Not reported</option>{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>;
 return <details><summary>Optional visa and funding context</summary><p>Your reports help scope current guidance. They do not establish mission responsibility, visa obligation or an exemption, and are optional for academic assessment.</p>
 {select("kind",[["appointment","Visa procedure"],["funding","Funding alternatives"],["visa_fee","Visa fee"]])}
 {c?.kind&&select("purpose",[["study","Degree studies"],["preparatory_study","Preparatory college"],["study_language","Language for intended studies"],["other","Another purpose"],["unknown","Cannot confirm"]])}
 {c?.purpose&&select("mission",answers.visaApplicationCountry==="in"?[["new_delhi","New Delhi"],["bengaluru","Bengaluru"],["chennai","Chennai"],["kolkata","Kolkata"],["mumbai","Mumbai"],["other","Another mission"],["unknown","Cannot confirm"]]:answers.visaApplicationCountry==="pk"?[["islamabad","Islamabad"],["karachi","Karachi"],["other","Another mission"],["unknown","Cannot confirm"]]:answers.visaApplicationCountry==="sa"?[["riyadh","Riyadh"],["jeddah","Jeddah"],["other","Another mission"],["unknown","Cannot confirm"]]:[["other","Another mission"],["unknown","Cannot confirm"]])}
 {c?.mission&&<label>Do the mission instructions apply to your reported residence and purpose?<select value={c.missionConfirmed===undefined?"unknown":String(c.missionConfirmed)} onChange={e=>onChange(withProcessContext(answers,"missionConfirmed",e.target.value==="unknown"?undefined:e.target.value==="true"))}><option value="unknown">Cannot confirm</option><option value="true">I report that they apply</option><option value="false">They do not apply</option></select></label>}
 {c?.kind==="visa_fee"&&select("ageBracket",[["under18","Under 18"],["exact18","Exactly 18"],["over18","Over 18"],["unknown","Cannot confirm"]])}
 {c?.kind==="funding"&&select("fundingMethod",[["blocked_account","Blocked account"],["scholarship","Scholarship"],["commitment","Formal commitment"],["loan","Education loan only"],["other","Another method"],["unknown","Cannot confirm"]])}
 {(c?.kind==="visa_fee"||c?.kind==="funding")&&select("exception",[["none","I report no applicable exception"],["public_scholarship","Public scholarship; coverage needs confirmation"],["other","Another possible exception"],["unknown","Cannot confirm"]])}
 <p><a href="https://www.auswaertiges-amt.de/en/visa-service">Confirm with the responsible mission</a></p></details>;
}
